<?php

// autoload_static.php @generated by Composer

namespace AdvancedAdsTracking\Composer\Autoload;

class ComposerStaticInit_advanced_ads_tracking
{
    public static $classMap = array (
        'Advanced_Ads_Tracking' => __DIR__ . '/../..' . '/public/public.php',
        'Advanced_Ads_Tracking_Admin' => __DIR__ . '/../..' . '/admin/admin.php',
        'Advanced_Ads_Tracking_Ajax' => __DIR__ . '/../..' . '/classes/ajax.php',
        'Advanced_Ads_Tracking_Amp' => __DIR__ . '/../..' . '/classes/amp.php',
        'Advanced_Ads_Tracking_Compatibility' => __DIR__ . '/../..' . '/classes/compatibility.php',
        'Advanced_Ads_Tracking_Dbop' => __DIR__ . '/../..' . '/classes/db-operations.php',
        'Advanced_Ads_Tracking_Debugger' => __DIR__ . '/../..' . '/classes/debugger.php',
        'Advanced_Ads_Tracking_Installer' => __DIR__ . '/../..' . '/classes/installer.php',
        'Advanced_Ads_Tracking_Limiter' => __DIR__ . '/../..' . '/classes/limiter.php',
        'Advanced_Ads_Tracking_Plugin' => __DIR__ . '/../..' . '/classes/plugin.php',
        'Advanced_Ads_Tracking_Public_Stats' => __DIR__ . '/../..' . '/classes/public-stats.php',
        'Advanced_Ads_Tracking_Util' => __DIR__ . '/../..' . '/classes/util.php',

    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_tracking::$classMap;

        }, null, ClassLoader::class);
    }
}
