<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Advanced_Ads_Tracking' => $baseDir . '/public/public.php',
    'Advanced_Ads_Tracking_Admin' => $baseDir . '/admin/admin.php',
    'Advanced_Ads_Tracking_Ajax' => $baseDir . '/classes/ajax.php',
    'Advanced_Ads_Tracking_Amp' => $baseDir . '/classes/amp.php',
    'Advanced_Ads_Tracking_Compatibility' => $baseDir . '/classes/compatibility.php',
    'Advanced_Ads_Tracking_Dbop' => $baseDir . '/classes/db-operations.php',
    'Advanced_Ads_Tracking_Debugger' => $baseDir . '/classes/debugger.php',
    'Advanced_Ads_Tracking_Installer' => $baseDir . '/classes/installer.php',
    'Advanced_Ads_Tracking_Limiter' => $baseDir . '/classes/limiter.php',
    'Advanced_Ads_Tracking_Plugin' => $baseDir . '/classes/plugin.php',
    'Advanced_Ads_Tracking_Public_Stats' => $baseDir . '/classes/public-stats.php',
    'Advanced_Ads_Tracking_Util' => $baseDir . '/classes/util.php',

);
