<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit_advanced_ads_tracking
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('AdvancedAdsTracking\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \AdvancedAdsTracking\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit_advanced_ads_tracking', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \AdvancedAdsTracking\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit_advanced_ads_tracking', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\AdvancedAdsTracking\Composer\Autoload\ComposerStaticInit_advanced_ads_tracking::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
