<?php
/**
 * Markup for tracking by user role setting
 *
 * @var Advanced_Ads_Tracking_Admin $this
 * @var array                       $disabled_roles list of user roles with tracking disabled
 * @var WP_Roles                    $roles          list of user roles
 * @var array                       $options        plugin options
 */

?>
<div id="advads-settings-track-by-user-role">
	<?php foreach ( $roles->roles as $slug => $user_role ) : ?>
		<label>
			<input type="checkbox" name="<?php echo esc_attr( $this->plugin->options_slug . '[disabled-roles][]' ); ?>"
				   value="<?php echo esc_attr( $slug ); ?>" <?php checked( in_array( $slug, $disabled_roles, true ) ); ?> />
			<?php echo esc_html( $user_role['name'] ); ?>
		</label>
	<?php endforeach; ?>
</div>
<p class="description">
	<?php
	esc_html_e(
		'Select specific roles to deactivate the click and impression tracking. In cases where a user possesses multiple roles and tracking is disabled for at least one of them, Advanced Ads will refrain from tracking any ad clicks or impressions generated by that user.',
		'advanced-ads-tracking'
	);
	?>
</p>
